version: '3.1'

services:
  api:
    image: golang:1.12
    command: go run main.go
    volumes:
      - ./api:/go/src/app
    working_dir: /go/src/app
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5432:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d/