version: '2'

services:
  frontend-base:
    image: node:11
    volumes:
      - ./frontend:/app
    working_dir: /app
  frontend-install:
    extends:
      service: frontend-base
    command: npm install
  # frontend-build:
  #   extends:
  #     service: frontend-base
  #   command: npm run build